export enum EnterpriseRoute {
  Workspace = '/workspace',
  Chat = '/workspace/chat',
  Platform = '/enterprise/platform',
  Gallery = '/workspace/gallery',
  Agents = '/enterprise/agents',
  Dashboard = '/enterprise/dashboard',
  ScheduledTasks = '/enterprise/scheduled-tasks',
  Memories = '/enterprise/memories',
  Feedback = '/enterprise/feedback',
  Channels = '/enterprise/channels',
  Knowledge = '/enterprise/knowledge',
  GeneralSkills = '/enterprise/general-skills',
  Skills = '/enterprise/skills',
  Tools = '/enterprise/tools',
  SystemManagement = '/enterprise/system-management',
  Accounts = '/enterprise/system-management/accounts',
  Models = '/enterprise/system-management/models',
  RuntimeSettings = '/enterprise/runtime-settings',
}
